---
language: generic # no frills build 
os: linux
dist: bionic

linux-ppc64le: &linux-ppc64le
  os: linux-ppc64le

linux-s390x: &linux-s390x
  os: linux
  arch: s390x
  dist: bionic

jobs:
  include:
    - <<: *linux-ppc64le
      script: echo hello testing
    - <<: *linux-ppc64le
      script: echo hello testing
    - <<: *linux-s390x
      script: echo hello testing
    - <<: *linux-s390x

script: true
